# Generated by Django 6.1.1 on 2026-09-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('company_size', models.CharField(max_length=100)),
                ('departments', models.JSONField(default=list)),
                ('automation_level', models.CharField(max_length=100)),
                ('repetitive_activities', models.JSONField(default=list)),
                ('workflow_notes', models.TextField(blank=True, max_length=500)),
                ('challenges', models.JSONField(default=list)),
                ('challenge_notes', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
