# Generated by Django 6.1.1 on 2026-09-15 05:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('company_name', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('company_size', models.CharField(max_length=50)),
                ('departments_selected', models.JSONField(blank=True, default=list)),
                ('additional_notes', models.TextField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=200)),
                ('utm_medium', models.CharField(blank=True, max_length=200)),
                ('utm_campaign', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prelim_report_sent', models.BooleanField(default=False)),
                ('full_report_sent', models.BooleanField(default=False)),
                ('full_report_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessment submissions'},
        ),
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.IntegerField(default=0)),
                ('department_scores', models.JSONField(blank=True, default=dict)),
                ('should_automate', models.JSONField(blank=True, default=list)),
                ('should_not_automate', models.JSONField(blank=True, default=list)),
                ('estimated_hours_saved_monthly', models.IntegerField(default=0)),
                ('estimated_cost_saved_monthly_inr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ai_summary', models.TextField(blank=True)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_report', to='assessments.lead')),
            ],
        ),
    ]
