# Generated by Django 6.1.1 on 2026-09-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_lead_alter_assessment_options_assessmentreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentreport',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Assessment Report', 'verbose_name_plural': 'Assessment Reports'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AddField(
            model_name='lead',
            name='automation_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='challenge_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='challenges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='repetitive_activities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='workflow_notes',
            field=models.TextField(blank=True),
        ),
    ]
