# Generated by Django 6.1.1 on 2026-09-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_assessmentreport_options_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessment submissions'},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='automation_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='challenges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='departments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='repetitive_activities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
